### ISSUE TITLE
svelte-fomantic-ui-jquery.js not found

### ISSUE THREAD

**Issue by AdrienLF** [roycdaviesuoa/svelte-fomantic-ui#2]
Hello! 

First of all, great initiative, and I can't wait to use it in my own svelte projects. 
I tried to follow the installation in the readme, however I have some issues. svelte-fomantic-ui-jquery.js is not found in the lib folder.

I do have this file, at this path: node_modules/svelte-fomantic-ui/src/lib/svelte-fomantic-ui-jquery.js

Here's what I have:

```bash 

11:53:47 AM [vite] page reload .svelte-kit/generated/server/internal.js
Error: Not found: /node_modules/svelte-fomantic-ui/src/lib/svelte-fomantic-ui-jquery.js
    at resolve (/Users/adrienlefalher/CODE/SvelteBase/my-app/node_modules/@sveltejs/kit/src/runtime/server/respond.js:473:13)
    at resolve (/Users/adrienlefalher/CODE/SvelteBase/my-app/node_modules/@sveltejs/kit/src/runtime/server/respond.js:282:5)
    at #options.hooks.handle (/Users/adrienlefalher/CODE/SvelteBase/my-app/node_modules/@sveltejs/kit/src/runtime/server/index.js:56:56)
    at Module.respond (/Users/adrienlefalher/CODE/SvelteBase/my-app/node_modules/@sveltejs/kit/src/runtime/server/respond.js:279:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I installed with `yarn add svelte-fomantic-ui`, and here is what I got:

```bash
yarn add v1.22.19
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning svelte-fomantic-ui > vite-plugin-svelte@3.0.1: use @sveltejs/vite-plugin-svelte for vite2.0+ support
warning svelte-fomantic-ui > vite-plugin-svelte > rollup-plugin-svelte > sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "svelte-fomantic-ui > svelte-preprocess@5.0.4" has unmet peer dependency "svelte@^3.23.0 || ^4.0.0-next.0 || ^4.0.0".
warning "svelte-fomantic-ui > vite-plugin-svelte@3.0.1" has unmet peer dependency "svelte@^3.0.0".
warning "svelte-fomantic-ui > vite-plugin-svelte@3.0.1" has unmet peer dependency "vite@>=0.20.8 <2.0.0".
warning "svelte-fomantic-ui > vite-plugin-svelte > svelte-hmr@0.11.6" has unmet peer dependency "svelte@>=3.19.0".
warning "svelte-fomantic-ui > vite-plugin-svelte > rollup-plugin-svelte@6.1.1" has unmet peer dependency "svelte@*".
warning "svelte-fomantic-ui > vite-plugin-svelte > rollup-plugin-svelte@6.1.1" has unmet peer dependency "rollup@>=1.19.2".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 35 new dependencies.
info Direct dependencies
└─ svelte-fomantic-ui@0.3.2
info All dependencies
├─ @jridgewell/sourcemap-codec@1.4.15
├─ @types/pug@2.0.6
├─ balanced-match@1.0.2
├─ brace-expansion@1.1.11
├─ buffer-crc32@0.2.13
├─ concat-map@0.0.1
├─ detect-indent@6.1.0
├─ es6-promise@3.3.1
├─ estree-walker@0.6.1
├─ fs.realpath@1.0.0
├─ glob@7.2.3
├─ graceful-fs@4.2.11
├─ inflight@1.0.6
├─ inherits@2.0.4
├─ magic-string@0.27.0
├─ min-indent@1.0.1
├─ minimatch@3.1.2
├─ minimist@1.2.8
├─ mkdirp@0.5.6
├─ path-is-absolute@1.0.1
├─ prism-svelte@0.4.7
├─ prismjs@1.29.0
├─ require-relative@0.8.7
├─ rimraf@2.7.1
├─ rollup-plugin-svelte@6.1.1
├─ rollup-pluginutils@2.8.2
├─ sander@0.5.1
├─ sorcery@0.11.0
├─ sourcemap-codec@1.4.8
├─ strip-indent@3.0.0
├─ svelte-fomantic-ui@0.3.2
├─ svelte-hmr@0.11.6
├─ svelte-preprocess@5.0.4
├─ svelte-prism@1.1.6
└─ vite-plugin-svelte@3.0.1
✨  Done in 3.88s.
```

Note that this is on a fresh svelte project, started like so:

```bash
npm create svelte@latest my-app
cd my-app
npm install
npm run dev
```

**Comment by roycdaviesuoa** [comment]
I will investigate and get back to you.  Stand by.

**Comment by roycdaviesuoa** [comment]
First, just checking what works (because this is how I have been doing it).  These is the procedure I have used to create a functioning project using svelte-fomantic-ui.

1. yarn create vite my-app2 --template svelte-ts
2. cd my-app2
3. yarn
4. yarn add svelte-fomantic-ui
5. Add the following lines to the index.html file (in the head section) 

```
<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/fomantic-ui@2.9.2/dist/semantic.min.css">
<script src="https://cdn.jsdelivr.net/npm/fomantic-ui@2.9.2/dist/semantic.min.js"></script>
<script type="module" src="node_modules/svelte-fomantic-ui/src/lib/svelte-fomantic-ui-jquery.js"></script>
```

6) Modify the App.svelte file by adding the following lines:

`  import { Button } from 'svelte-fomantic-ui';
`
to the script section, and

`  <Button ui red>A Fomantic UI Button</Button>
`
to the main section.

7) yarn run dev

This results in a standard svelte app using typescript.

**Comment by roycdaviesuoa** [comment]
When I follow your instructions - one point to note - I understand it is not wise to mix npm and yarn, so I used yarn only:

```
yarn create svelte@latest my-app3
cd my-app3
yarn
yarn add svelte-fomantic-ui
```

and adding 

```
<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/fomantic-ui@2.9.2/dist/semantic.min.css">
<script src="https://cdn.jsdelivr.net/npm/fomantic-ui@2.9.2/dist/semantic.min.js"></script>
<script type="module" src="node_modules/svelte-fomantic-ui/src/lib/svelte-fomantic-ui-jquery.js"></script>
```

to app.html and then

```
<script lang="ts">
    import { Button } from 'svelte-fomantic-ui';
</script>
```

to +page.svelte, before running

`yarn dev`

The error I get is that '$ is not defined'

This is because sveltekit supports server-side-rendering by default, and in that case, jquery is not available.  

Fomantic UI, however, is heavily dependent on jquery, so at this stage, I would have to say that it cannot be used in this way at present, but I will investigate whether it may be possible.

That said, I note that the documentation is not clear on this point, so will update accordingly.

**Comment by roycdaviesuoa** [comment]
The core difference between the following commands:

`yarn create svelte@latest my-app3`

and

`yarn create vite my-app2 --template svelte-ts`

is that the former creates a Server Side Rendered App based on SvelteKit whereas the latter creates a Client side WebApp based on Vite.

**Comment by roycdaviesuoa** [comment]
As an aside, if you really want to use fomantic ui in a server-side rendered app, you can at least use standard fomantic-ui by adding it using `yarn add fomantic-ui`, but the modules such as popup, calendar, accordian and many others (which depend on jquery) will not work.  Only those variations that don't require javascript to be run that initialises the module will work.

+page.svelte can then be modified to:

```
<script lang="ts">
    import 'fomantic-ui/dist/semantic.min.css';
  
    let someText = 'Hello World';
</script>


<h1>Welcome to SvelteKit</h1>
<p>Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation</p>

<buttons class="ui">
    <button class="ui button red" on:click={() => someText="Button 1 clicked"}>Click Here</button>
    <button class="ui button green" on:click={() => someText="Button 2 clicked"}>Click Here too</button>
    <h2 class="ui blue header">{someText}</h2>
</buttons>
```

**Comment by mtayyabviz** [comment]
I think you can disable SSR in SvelteKit in favor of client-side rendering with SvelteKit with just one line...

Actually, I got Jquery stuff working like popup. I put the following code with `src` folder of the SvelteKit app:

```js
export function handle({ request, resolve }) {
    return resolve(request, { ssr: false });
  }
```


But, only issue I am facing right now is to refresh my webpage twice sometime to get jquery work. Any thoughts?

**Comment by roycdaviesuoa** [comment]
Hi, Mohammed,

Indeed, sveltekit is made to potentially work with SSR, however, svelte-fomantic-ui was not designed to work that way.  It might work, but I wouldn't gaurantee it, and it hasn't been tested for that.

I generally use it with elixir phoenix framework, with a graphql api wrapped around the server for use by many types of user apps, not just webapps.

That said, anyone willing to tweak and adapt svelte-fomantic-ui for SSR, I'd be happy to open up the repository to have a go.

/Roy

--
Dr. Roy C. Davies
Senior Technician, Smart Digital Lab, University of Auckland
***@***.***
+64 27 7795294
https://nz.linkedin.com/in/roycdavies
________________________________

**Comment by mtayyabviz** [comment]
Hi Roy,

Yes, I am SvelteKit to work an SPA, nothing backend functionality I really need. Because, I will use .Net Core Web API behind it :)

I am open to tweak this to my level of experience within JavaScript.

Thank you,
Tayyab

**Comment by roycdavies** [comment]
Hi Tayyab,

Have you worked on repositories before?  We could make a branch for you to work with, and all looking good, could merge back in.  Or,  you could work locally and then do a pull request.

**Comment by mtayyabviz** [comment]
Hi Roy,

Yes, I work within private repositories for apps I am working on. Also, I would be glad to work within your repo's new branch to propose some improvements according to my expertise  :)

**Comment by roycdaviesuoa** [comment]
Hi,

Sounds good.  What sorts of projects are you working on?  I work across multiple platforms and projects, from VR / MR to distributed systems to IoT devices, and everything in between.

You can see more about me at roycdavies.github.io

A suggested way forward is for you to make a local branch and work in that branch.  When you have got far enough forward that there is something to test, we can then see about how that might be further refined and potentially incorporated into the main branch.

A first step would be to clarify in what ways the current set up doesn't work in SSR mode, and why.  I haven't fully investigated yet as that was not the focus.  Note that there are many different SSR systems, so what works for one might not work for another.

/Roy.


--

Dr. Roy C. Davies

Senior Technician, Smart Digital Lab,

University of Auckland.



E: ***@***.******@***.***>

P: 0277795294

R: 405:1122 (405:979 Smart Digital Lab)

https://nz.linkedin.com/in/roycdavies



________________________________

**Comment by mtayyabviz** [comment]
Hi Roy,

I am actually converting an already done app within MS Access to SvelteKit and .Net Core. Also, I really don't need SSR features of SvelteKit that's why I disabled it. So, I didn't got into much details whether it works in SSR mode correctly or not.

I will definitely create a local branch as I find any issues that I can fix easily, for other issues where I will get confused, I will ask you here. Again, I have to find time for it as well :)

I will update as I make any progress
